#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MasonJar.Resource", IsApplication=true)]

namespace MasonJar
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Outcoder.Resource.String.ApplicationName = global::MasonJar.Resource.String.ApplicationName;
			global::Outcoder.Resource.String.Hello = global::MasonJar.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fadein = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fadeout = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int add_hover = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int add_normal = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int add_pressed = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int addbutton = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int arrow_bent = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int arrow_right = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int arrow_up = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Background = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int brightness = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int circle = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int darkborder = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int edit = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int edit_hover = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int edit_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int edit_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int editbutton = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int help = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int help_hover = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int help_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int help_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int helpbutton = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int history = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int history_hover = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int history_normal = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int history_pressed = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int historybutton = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Icon = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int Jar = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int picnicbkg = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int stick = 2130837534;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int button_edit = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int button_help = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int button_history = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int edit_button_add_category = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int edit_button_add_item = 2131099650;
			
			// aapt resource value: 0x7f06000c
			public const int help_content_parent = 2131099660;
			
			// aapt resource value: 0x7f060006
			public const int history_category_swatch = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int history_category_timestamp = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int history_category_title = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int history_content = 2131099652;
			
			// aapt resource value: 0x7f06000b
			public const int imageView1 = 2131099659;
			
			// aapt resource value: 0x7f060000
			public const int maineditlayout = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int mainlayout = 2131099655;
			
			// aapt resource value: 0x7f06000d
			public const int tutorial_step1 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int tutorial_step2 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int tutorial_step3 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int tutorial_step4 = 2131099664;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Edit = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EditCategory = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditHeaderCategories = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditHeaderItems = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EditItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int History = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int HistoryItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int HistoryItemWithCategory = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int tutorial_step1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int tutorial_step2 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int tutorial_step3 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int tutorial_step4 = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
