#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MasonJar.Resource", IsApplication=true)]

namespace MasonJar
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int brightness = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edit = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int edit_hover = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int edit_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int edit_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int editbutton = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int help = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int help_hover = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int help_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int help_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int helpbutton = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int history = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int history_hover = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int history_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int history_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int historybutton = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Icon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int picnicbkg = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int button_edit = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int button_help = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int button_history = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int mainlayout = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
