#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MasonJar.Resource", IsApplication=true)]

namespace MasonJar
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Outcoder.Resource.String.ApplicationName = global::MasonJar.Resource.String.ApplicationName;
			global::Outcoder.Resource.String.Hello = global::MasonJar.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fadein = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int fadeout = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int add_hover = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int add_normal = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int add_pressed = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int addbutton = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int arrow_bent = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int arrow_right = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int arrow_up = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Background = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int border_black = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int brightness = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int circle = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int circle_dashed = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int circle_outline = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int darkborder = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int edit = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int edit_hover = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int edit_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int edit_pressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int editbutton = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int help = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int help_hover = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int help_normal = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int help_pressed = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int helpbutton = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int history = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int history_hover = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int history_normal = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int history_pressed = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int historybutton = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Icon = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Jar = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int picnicbkg = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int stick = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int swatch = 2130837538;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060035
			public const int button_edit = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int button_help = 2131099702;
			
			// aapt resource value: 0x7f060034
			public const int button_history = 2131099700;
			
			// aapt resource value: 0x7f060027
			public const int edit_button_add_category = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int edit_button_add_item = 2131099688;
			
			// aapt resource value: 0x7f060026
			public const int edit_category_delete = 2131099686;
			
			// aapt resource value: 0x7f060024
			public const int edit_category_swatch = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int edit_category_title = 2131099685;
			
			// aapt resource value: 0x7f06002a
			public const int edit_item_content = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int edit_item_delete = 2131099691;
			
			// aapt resource value: 0x7f060029
			public const int edit_item_swatch = 2131099689;
			
			// aapt resource value: 0x7f060001
			public const int edit_overlay_category_delete = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int edit_overlay_category_delete_no = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int edit_overlay_category_delete_yes = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int edit_overlay_category_rename = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int edit_overlay_category_rename_edit = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int edit_overlay_category_rename_no = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int edit_overlay_category_rename_yes = 2131099657;
			
			// aapt resource value: 0x7f06000f
			public const int edit_overlay_category_swatch = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int edit_overlay_category_swatch_1 = 2131099664;
			
			// aapt resource value: 0x7f060019
			public const int edit_overlay_category_swatch_10 = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int edit_overlay_category_swatch_11 = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int edit_overlay_category_swatch_12 = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int edit_overlay_category_swatch_13 = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int edit_overlay_category_swatch_14 = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int edit_overlay_category_swatch_15 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int edit_overlay_category_swatch_16 = 2131099679;
			
			// aapt resource value: 0x7f060011
			public const int edit_overlay_category_swatch_2 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int edit_overlay_category_swatch_3 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int edit_overlay_category_swatch_4 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int edit_overlay_category_swatch_5 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int edit_overlay_category_swatch_6 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int edit_overlay_category_swatch_7 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int edit_overlay_category_swatch_8 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int edit_overlay_category_swatch_9 = 2131099672;
			
			// aapt resource value: 0x7f060020
			public const int edit_overlay_category_swatch_cancel = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int edit_overlay_item_category = 2131099681;
			
			// aapt resource value: 0x7f060023
			public const int edit_overlay_item_category_cancel = 2131099683;
			
			// aapt resource value: 0x7f060022
			public const int edit_overlay_item_category_list = 2131099682;
			
			// aapt resource value: 0x7f060004
			public const int edit_overlay_item_delete = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int edit_overlay_item_delete_no = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int edit_overlay_item_delete_yes = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int edit_overlay_item_rename = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int edit_overlay_item_rename_edit = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int edit_overlay_item_rename_no = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int edit_overlay_item_rename_yes = 2131099661;
			
			// aapt resource value: 0x7f06002c
			public const int edit_selectable_category = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int edit_selectable_category_swatch = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int edit_selectable_category_title = 2131099694;
			
			// aapt resource value: 0x7f060038
			public const int help_content_parent = 2131099704;
			
			// aapt resource value: 0x7f060032
			public const int history_category_swatch = 2131099698;
			
			// aapt resource value: 0x7f06002f
			public const int history_category_timestamp = 2131099695;
			
			// aapt resource value: 0x7f060031
			public const int history_category_title = 2131099697;
			
			// aapt resource value: 0x7f060030
			public const int history_content = 2131099696;
			
			// aapt resource value: 0x7f060037
			public const int imageView1 = 2131099703;
			
			// aapt resource value: 0x7f060000
			public const int maineditlayout = 2131099648;
			
			// aapt resource value: 0x7f060033
			public const int mainlayout = 2131099699;
			
			// aapt resource value: 0x7f060039
			public const int tutorial_step1 = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int tutorial_step2 = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int tutorial_step3 = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int tutorial_step4 = 2131099708;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Edit = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EditCategory = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EditHeaderCategories = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EditHeaderItems = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EditItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int EditSelectableCategory = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int History = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int HistoryItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int HistoryItemWithCategory = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Main = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int tutorial_step1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int tutorial_step2 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int tutorial_step3 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int tutorial_step4 = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
